---
# Ansible playbook to install software on your mac in one go!
- hosts: localhost
  connection: local

  vars:
    - homedir: "{{ lookup('env','HOME') }}"

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.homebrew

#### Enable these in your own fork.#
  tasks:
    - include: defaults.yml
  #  - include: network.yml
  #  - include: security.yml

