---
# Ansible playbook to install software on your mac in one go!
- hosts: localhost
  connection: local

  vars:
    - homedir: "{{ lookup('env','HOME') }}"

  vars_files:
    - vars/main.yml
    - "{{homedir}}/mac_settings.yml"

  roles:
    - geerlingguy.homebrew

  tasks:

    - include: security.yml

    - include: defaults.yml


