#!/usr/bin/env ansible-playbook -l localhost -c local -K

# Ansible playbook to install software on your mac in one go!
- name: Installing software on your Mac.
  hosts: localhost
  connection: local

  vars:
    - homedir: "{{ lookup('env','HOME') }}"

  vars_files:
    - vars/main.yml
    - vars/settings.yml

  roles:
    - geerlingguy.homebrew

  tasks:
    - include: installer.yml
 #   - include: security.yml
 #   - include: defaults.yml
 #   - include: network.yml
