---
# Ansible playbook to secure your mac in one go!

  - name: "Block snooping in home directories."
    file:
      mode: 700
      path: "{{ homedir }}/{{ item }}"
    with_items:
      - Library
      - Documents
      - Desktop
      - Downloads
      - Pictures
      - Movies
      - Appications

    become: yes

  - name: "Set permission on Users Shared."
    command: chmod 1777 /Users/Shared
    become: yes

  - name: "Set wake on lan."
    command: "systemsetup -setwakeonnetworkaccess on"
    become: yes

  - name: "Enable Gatekeeper."
    shell: /usr/sbin/spctl --master-enable
    become: yes

  - name: "Allow signed apps with Gatekeeper."
    shell:  /usr/sbin/spctl --enable --label 'Developer ID'
    become: yes
